### ISSUE TITLE
Why is a Teensy 4.1 needed instead of a 2.0

### ISSUE THREAD

**Issue by Invictaz** [Ryzee119/usb64#37]
I have seen many controller emulators. Why is a Teensy 4.1 needed instead of a 2.0 version?

**Comment by Ryzee119** [comment]
Speed, ram capacity, dual usb otg, memory mapped qspi are in Teensy4.1 and not teensy2.

**Comment by Ryzee119** [comment]
This board loads of features that i have never seen in more basic adaptors like tpak, mempak emulation etc. So the extra power is beneficial
