### ISSUE TITLE
Possibility of porting the project to other development boards

### ISSUE THREAD

**Issue by rodolfostanic** [Ryzee119/usb64#38]
Because of the global chip shortage, PJRC is having issues to maintain the Teensy 4.1 in stock. 

Is it possible to replace it with another board, maybe an Arduino based one?

**Comment by Ryzee119** [comment]
To be honest im not planning on  putting in the work to do this but am open to PRs.

Note the requirements for this project are high. Dual OTG USB, a few MB RAM atleast, sd card slot etc. The speed of the teensy isnt necessarily needed, but it does help.

The global chip shortage will prob affect the next chip i pick too 🙃

**Comment by rodolfostanic** [comment]
Got it, makes sense. Thanks for all the effort you put into this project so far! 😊
