### ISSUE TITLE
Some Questions

### ISSUE THREAD

**Issue by conkydong** [Ryzee119/usb64#41]
Hi!
Really great project that you have there!

Just one or two questions:
1. Is it possible to run multiple bluetooth gamepads at the same time?
2. Would it be somehow feasible to implement basic multiplayer over the internet, be it over wifi or cable? 

Regards

**Comment by Ryzee119** [comment]
1. Currently bluetooth support is provided by using the wireless 8bitdo adaptor. These only support one controller. To support multiple usb controllers you can use multiple 8bitdo adaptors via a USB hub.

2. I guess its feasible. It requires a lot of other aspects outside the scope of this project. Its not currently supported.
