### ISSUE TITLE
Power from 3.3v

### ISSUE THREAD

**Issue by nmcgill** [Ryzee119/usb64#58]
Based on [this](https://forum.pjrc.com/threads/60373-Can-t-program-Teensy-4-0-after-Vin-trace-is-cut-and-supplyng-external-3-3v?p=235792&viewfull=1#post235792) I am wondering if the Teensy 4.1 can be powered through the controller 3.3V line, in addition to a 3V coin cell battery for RTC & power management, replacing the need for VUSB.

It would look along the lines of:
- N64 Controller 3.3V to Teensy 3.3V pin (above pin 23)
- 3V Coin cell to Teensy VBAT pin

Something I was considering to try - but I am also wondering if someone with more knowledge might know if this is feasible or not.

**Comment by Ryzee119** [comment]
The USB port requires 5V so you'd to start messing around with boost converters etc.

It is possible but starts getting messy.

This project just uses an external 5v source for simplicity and minimal stress on the n64.
